"""
AgentX — Agent 9: PR Creator
Phase 09 — Pull Request Creation

Responsibilities:
- Create feature branch with Conventional Commits format
- Commit all verified patches
- Generate academic-quality PR body with:
  - Root Cause Analysis summary
  - Test results and verification report
  - Severity badges (CRITICAL/HIGH/MEDIUM/LOW)
  - Confidence scores per fix
  - Researcher approval checkpoint (draft PR)
- Generate PDF report via Jinja2 + WeasyPrint
- Store all artefacts in Supabase

Tools: PyGitHub, GitPython, Jinja2, GitHub REST API, Supabase
"""

from __future__ import annotations

import asyncio
import os
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from jinja2 import Environment, FileSystemLoader, select_autoescape

from config.settings import settings
from core.base_agent import BaseAgent
from core.logging import get_logger
from core.state import AgentXState
from db.database import get_db_session
from db.models import PatchStatus, RunStatus
from db.repositories import RunRepository
from services.github.github_service import GitHubService

logger = get_logger(__name__)

# Severity badge map for GitHub PR markdown
SEVERITY_BADGES = {
    "CRITICAL": "![CRITICAL](https://img.shields.io/badge/severity-CRITICAL-darkred)",
    "HIGH": "![HIGH](https://img.shields.io/badge/severity-HIGH-red)",
    "MEDIUM": "![MEDIUM](https://img.shields.io/badge/severity-MEDIUM-orange)",
    "LOW": "![LOW](https://img.shields.io/badge/severity-LOW-yellow)",
    "INFO": "![INFO](https://img.shields.io/badge/severity-INFO-blue)",
}

PR_BODY_TEMPLATE = """\
# 🤖 AgentX Autonomous Code Review — Run `{{ run_id }}`

> **Generated by AgentX** | Agentic AI Pipeline | {{ timestamp }}
> Pipeline: LangGraph 9-Agent | LLM: Groq Llama 3.3 70B | Cost: Rs. 0

---

## 📊 Summary

| Metric | Value |
|--------|-------|
| Total Issues Found | {{ total_issues }} |
| Fixes Generated | {{ total_fixes }} |
| Fixes Approved | {{ approved_fixes }} |
| Overall Confidence | {{ overall_confidence }}% |
| Safe to Merge | {{ safe_badge }} |
| Verification | {{ verification_summary }} |

---

## 🔍 Issues Fixed

{% for fix in fixes %}
### {{ loop.index }}. {{ fix.severity_badge }} {{ fix.title }}

**File**: `{{ fix.file_path }}`{% if fix.line_start %} **Line**: {{ fix.line_start }}{% endif %}
**Type**: `{{ fix.issue_type }}`{% if fix.ml_pattern %} **ML Pattern**: `{{ fix.ml_pattern }}`{% endif %}
**Confidence**: `{{ fix.confidence }}%` | **Risk**: `{{ fix.risk_level }}`

#### Root Cause Analysis

| Stage | Detail |
|-------|--------|
| **Origin** | {{ fix.rca_origin }} |
| **Propagation** | {{ fix.rca_propagation }} |
| **Manifestation** | {{ fix.rca_manifestation }} |
| **Impact** | {{ fix.rca_impact }} |

> 🔬 **Research Impact**: {{ fix.research_impact }}

#### Fix Applied

{{ fix.fix_explanation }}

```diff
{{ fix.diff_excerpt }}
```

#### Verification

- Tests Passed: ✅ `{{ fix.tests_passed }}`
- Tests Failed: {% if fix.tests_failed > 0 %}❌ `{{ fix.tests_failed }}`{% else %}✅ `0`{% endif %}
- Tests Generated: `{{ fix.tests_generated }}`
- Regression Detected: {% if fix.regression %}❌ **YES**{% else %}✅ **NO**{% endif %}

---
{% endfor %}

## ⚠️ Reviewer Notes

Please review each fix carefully before merging. These fixes are AI-generated and may require domain-specific validation.

- Static analysis: Pylint + Bandit
- Pattern detection: 8-pattern AST + Groq LLM
- Verification: Docker-isolated test execution

---

## 🔗 Resources

- **Full PDF Report**: Attached to this PR as an artefact
- **Audit Trail**: Stored in Supabase (Run ID: `{{ run_id }}`)
- **Pipeline**: AgentX — TriggeredAGIs | Agentic AI Hackathon 2026 | ASTRA Lab, IIT Madras

---
*Generated by [AgentX](https://github.com/agentx) — Autonomous Code Review Pipeline*
"""


class PRCreatorAgent(BaseAgent):
    """
    Agent 9 — PR Creator.
    Commits all verified patches and creates a structured GitHub PR.
    """

    agent_name = "PRCreator"
    phase = 9

    async def execute(self, state: AgentXState) -> AgentXState:
        """Create branch, commit patches, open draft PR, generate PDF report."""
        validated_patches: List[Dict] = state.get("validated_patches", [])
        ranked_issues: List[Dict] = state.get("ranked_issues", [])
        rca_reports: List[Dict] = state.get("rca_reports", [])
        verification_results: List[Dict] = state.get("verification_results", [])
        repo_path = state.get("repo_local_path", "")
        run_id = state["run_id"]
        repo_owner = state["repo_owner"]
        repo_name = state["repo_name"]
        repo_branch = state.get("repo_branch", "main")
        github_token = state.get("github_token", settings.github_default_token)
        state["current_phase"] = 9

        state = self._emit_progress(state, "Preparing PR branch and commits...")

        # Build lookup maps
        issues_by_id = {i["id"]: i for i in ranked_issues}
        rca_by_issue = {r["issue_id"]: r for r in rca_reports}
        verify_by_issue = {r.get("issue_id", ""): r for r in verification_results}

        # Only commit safe-to-merge patches (or all approved if no Docker)
        commit_patches = [
            p for p in validated_patches
            if p.get("status") not in (PatchStatus.HUMAN_REVIEW, "HUMAN_REVIEW")
            and p.get("fixed_code")
            and p.get("fixed_code") != p.get("original_code")
        ]

        if not commit_patches:
            state = self._emit_progress(state, "No patches to commit — all require human review.")
            state["pr_url"] = ""
            state["pr_number"] = 0
            state["pr_complete"] = True
            return state

        gh_service = GitHubService(github_token)

        # Create branch
        branch_name = f"agentx/fix-{run_id}"
        try:
            base_branch = gh_service.create_branch(
                owner=repo_owner,
                repo_name=repo_name,
                branch_name=branch_name,
                base_branch=repo_branch,
            )
        except Exception as exc:
            logger.error("branch_creation_failed", error=str(exc))
            state["error_message"] = f"Branch creation failed: {exc}"
            return state

        state["pr_branch"] = branch_name
        state = self._emit_progress(state, f"Branch created: {branch_name}")

        # Commit each patched file with Conventional Commits format
        committed_files = []
        for patch in commit_patches:
            issue = issues_by_id.get(patch.get("issue_id", ""), {})
            file_path = issue.get("file_path", "")
            if not file_path:
                continue

            commit_type = _get_commit_type(issue)
            commit_scope = Path(file_path).stem
            commit_msg = (
                f"{commit_type}({commit_scope}): fix {issue.get('title', 'issue').lower()[:60]}\n\n"
                f"Run-ID: {run_id}\n"
                f"Severity: {issue.get('severity', 'UNKNOWN')}\n"
                f"Confidence: {patch.get('validation_confidence', 0):.0f}%\n"
                f"AgentX auto-fix — {issue.get('description', '')[:200]}"
            )

            try:
                gh_service.commit_file(
                    owner=repo_owner,
                    repo_name=repo_name,
                    branch_name=branch_name,
                    file_path=file_path,
                    new_content=patch["fixed_code"],
                    commit_message=commit_msg,
                )
                committed_files.append(file_path)
                logger.info("file_committed", file=file_path, run_id=run_id)
            except Exception as exc:
                logger.warning("commit_failed", file=file_path, error=str(exc))

        if not committed_files:
            logger.warning("no_files_committed", run_id=run_id)

        state = self._emit_progress(
            state, f"Committed {len(committed_files)} files"
        )

        # Build PR body
        fix_contexts = self._build_fix_contexts(
            commit_patches, issues_by_id, rca_by_issue, verify_by_issue
        )
        pr_body = self._render_pr_body(
            run_id=run_id,
            fix_contexts=fix_contexts,
            total_issues=len(ranked_issues),
        )

        # PR title (Conventional Commits)
        severity_counts = {}
        for p in commit_patches:
            sev = issues_by_id.get(p.get("issue_id", ""), {}).get("severity", "UNKNOWN")
            severity_counts[sev] = severity_counts.get(sev, 0) + 1
        top_sev = max(severity_counts, key=severity_counts.get) if severity_counts else "UNKNOWN"
        pr_title = (
            f"fix(agentx): auto-fix {len(commit_patches)} bug(s) "
            f"[{top_sev}] — Run {run_id}"
        )

        # Create PR
        state = self._emit_progress(state, "Creating GitHub PR (draft)...")
        try:
            pr_url, pr_number = gh_service.create_pull_request(
                owner=repo_owner,
                repo_name=repo_name,
                head_branch=branch_name,
                base_branch=base_branch,
                title=pr_title,
                body=pr_body,
                draft=True,
            )
        except Exception as exc:
            logger.error("pr_creation_failed", error=str(exc))
            state["error_message"] = f"PR creation failed: {exc}"
            return state

        state["pr_url"] = pr_url
        state["pr_number"] = pr_number

        # Generate PDF report
        pdf_path = await self._generate_pdf_report(
            run_id=run_id,
            fix_contexts=fix_contexts,
            pr_url=pr_url,
            total_issues=len(ranked_issues),
        )
        state["pdf_report_path"] = pdf_path or ""

        # Persist to DB
        try:
            async with get_db_session() as session:
                runs_repo = RunRepository(session)
                await runs_repo.mark_complete(
                    run_id=run_id,
                    pr_url=pr_url,
                    pr_number=pr_number,
                )
        except Exception as exc:
            logger.warning("pr_db_persist_failed", error=str(exc))

        state["pr_complete"] = True
        state["status"] = RunStatus.PR_CREATED

        state = self._emit_progress(
            state,
            f"PR created: {pr_url}",
            {"pr_url": pr_url, "pr_number": pr_number},
        )
        logger.info("pr_created", run_id=run_id, pr_url=pr_url, pr_number=pr_number)
        return state

    def _build_fix_contexts(
        self,
        patches: List[Dict],
        issues_by_id: Dict,
        rca_by_issue: Dict,
        verify_by_issue: Dict,
    ) -> List[Dict]:
        """Build rich context dicts for each fix for PR body and PDF rendering."""
        contexts = []
        for patch in patches:
            issue_id = patch.get("issue_id", "")
            issue = issues_by_id.get(issue_id, {})
            rca = rca_by_issue.get(issue_id, {})
            verify = verify_by_issue.get(issue_id, {})

            severity = issue.get("severity", "UNKNOWN")
            confidence = patch.get("validation_confidence", 0)

            contexts.append({
                "title": issue.get("title", "Unknown Issue"),
                "file_path": issue.get("file_path", ""),
                "line_start": issue.get("line_start"),
                "issue_type": issue.get("issue_type", "UNKNOWN"),
                "ml_pattern": issue.get("ml_pattern"),
                "severity": severity,
                "severity_badge": SEVERITY_BADGES.get(severity, severity),
                "confidence": round(confidence),
                "risk_level": _confidence_to_risk(confidence),
                "fix_explanation": patch.get("fix_explanation", ""),
                "diff_excerpt": (patch.get("diff", "") or "")[:800],
                "rca_origin": rca.get("origin", "N/A")[:200],
                "rca_propagation": rca.get("propagation", "N/A")[:200],
                "rca_manifestation": rca.get("manifestation", "N/A")[:200],
                "rca_impact": rca.get("impact", "N/A")[:200],
                "research_impact": rca.get("research_impact_statement", "N/A")[:300],
                "tests_passed": verify.get("tests_passed", 0),
                "tests_failed": verify.get("tests_failed", 0),
                "tests_generated": verify.get("tests_generated", patch.get("tests_generated", 0)),
                "regression": verify.get("regression_detected", False),
            })
        return contexts

    def _render_pr_body(
        self,
        run_id: str,
        fix_contexts: List[Dict],
        total_issues: int,
    ) -> str:
        """Render Jinja2 PR body template."""
        from jinja2 import Template

        approved_fixes = len(fix_contexts)
        overall_conf = (
            sum(f["confidence"] for f in fix_contexts) / max(len(fix_contexts), 1)
        )
        total_passed = sum(f["tests_passed"] for f in fix_contexts)
        total_failed = sum(f["tests_failed"] for f in fix_contexts)
        safe = total_failed == 0

        tmpl = Template(PR_BODY_TEMPLATE)
        return tmpl.render(
            run_id=run_id,
            timestamp=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            total_issues=total_issues,
            total_fixes=approved_fixes,
            approved_fixes=approved_fixes,
            overall_confidence=round(overall_conf),
            safe_badge="✅ YES" if safe else "⚠️ REVIEW REQUIRED",
            verification_summary=f"{total_passed} passed / {total_failed} failed",
            fixes=fix_contexts,
        )

    async def _generate_pdf_report(
        self,
        run_id: str,
        fix_contexts: List[Dict],
        pr_url: str,
        total_issues: int,
    ) -> Optional[str]:
        """Generate a PDF report using ReportLab (WeasyPrint fallback)."""
        try:
            from reportlab.lib.pagesizes import A4
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib.units import cm
            from reportlab.lib import colors
            from reportlab.platypus import (
                SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
            )

            output_dir = Path("/tmp/agentx_reports")
            output_dir.mkdir(parents=True, exist_ok=True)
            pdf_path = output_dir / f"agentx_report_{run_id}.pdf"

            doc = SimpleDocTemplate(str(pdf_path), pagesize=A4)
            styles = getSampleStyleSheet()
            story = []

            # Title
            story.append(Paragraph(f"AgentX Code Review Report — Run {run_id}", styles["Title"]))
            story.append(Paragraph(
                f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} | PR: {pr_url}",
                styles["Normal"]
            ))
            story.append(Spacer(1, 0.5 * cm))

            # Summary table
            summary_data = [
                ["Metric", "Value"],
                ["Total Issues", str(total_issues)],
                ["Fixes Applied", str(len(fix_contexts))],
                ["PR URL", pr_url[:80]],
            ]
            tbl = Table(summary_data, colWidths=[7 * cm, 10 * cm])
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ]))
            story.append(tbl)
            story.append(Spacer(1, 0.5 * cm))

            # Per-fix details
            for i, fix in enumerate(fix_contexts, 1):
                story.append(Paragraph(
                    f"{i}. [{fix['severity']}] {fix['title']}", styles["Heading2"]
                ))
                story.append(Paragraph(f"File: {fix['file_path']}", styles["Normal"]))
                story.append(Paragraph(f"Confidence: {fix['confidence']}% | Risk: {fix['risk_level']}", styles["Normal"]))
                story.append(Paragraph(f"Origin: {fix['rca_origin']}", styles["Normal"]))
                story.append(Paragraph(f"Research Impact: {fix['research_impact']}", styles["Normal"]))
                story.append(Paragraph(f"Fix: {fix['fix_explanation']}", styles["Normal"]))
                story.append(Spacer(1, 0.3 * cm))

            doc.build(story)
            logger.info("pdf_report_generated", path=str(pdf_path), run_id=run_id)
            return str(pdf_path)

        except Exception as exc:
            logger.warning("pdf_generation_failed", error=str(exc))
            return None


def _get_commit_type(issue: Dict) -> str:
    """Map issue type to Conventional Commits type prefix."""
    severity = issue.get("severity", "").upper()
    issue_type = str(issue.get("issue_type", "")).upper()
    if "SECURITY" in issue_type:
        return "fix"
    if severity in ("CRITICAL", "HIGH"):
        return "fix"
    if "CODE_SMELL" in issue_type:
        return "refactor"
    return "fix"


def _confidence_to_risk(confidence: float) -> str:
    """Convert confidence score to human-readable risk level."""
    if confidence >= 90:
        return "LOW"
    if confidence >= 70:
        return "MEDIUM"
    return "HIGH"
